services:
  # frontend:
  #   build: 
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: krishi_frontend
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./frontend/app:/app
  #     - /app/node_modules
  #   env_file:
  #     - ./frontend/.env
  #   depends_on:
  #     - backend
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: krishi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env