// --- DETAILED DUMMY DATA ---

export const communityDetails = {
    1: { id: 1, name: "Wheat Growers of Punjab", members: 1250, description: "A community for wheat farmers in the Punjab region to discuss techniques and market trends.", icon: "🌾", },
    2: { id: 2, name: "Maharashtra Sugarcane Farmers", members: 8500, description: "Connecting sugarcane cultivators across Maharashtra for better yields and practices.", icon: "🌿", },
    3: { id: 3, name: "Organic Farming India", members: 25000, description: "A national community for everything related to organic and sustainable farming.", icon: "🌍", },
    4: { id: 4, name: "Cotton Cultivators Collective", members: 12000, description: "Focused on cotton farming, from pest control to market linkage.", icon: "-", },
    5: { id: 5, name: "Hydroponics Innovators", members: 5400, description: "Exploring the future of farming with soil-less cultivation techniques.", icon: "💧", },
    6: { id: 6, name: "Indian Dairy Farmers", members: 18000, description: "A place to discuss livestock health, milk production, and fodder management.", icon: "🐄" },
};

export const userJoinedCommunities = [1, 2];

export const communityQueries = {
    // Queries for "Wheat Growers of Punjab"
    1: [
        { id: 101, user: { name: "Balwinder Singh", avatar: "BS" }, query: "What is the best time to sow the HD-3086 wheat variety this year?", solutions: [{ user: { name: "Anita Desai", avatar: "AD" }, text: "The ideal window is between November 1st and November 15th for the Punjab region. Make sure soil moisture is good." }, { user: { name: "Raj Patel", avatar: "RP" }, text: "I agree with Anita. I got a 10% higher yield last year by sowing on Nov 5th." },] },
        { id: 102, user: { name: "Gurpreet Kaur", avatar: "GK" }, query: "Seeing signs of yellow rust on my crop. What's the most effective fungicide to use right now?", solutions: [{ user: { name: "S. Verma", avatar: "SV" }, text: "Propiconazole (Tilt) is very effective. Spray 200ml in 200 litres of water per acre. Act quickly!" }] },
        { id: 103, user: { name: "Hardeep Gill", avatar: "HG" }, query: "What is the recommended NPK fertilizer ratio for the first irrigation cycle?", solutions: [{ user: { name: "Dr. Alok Nath", avatar: "AN" }, text: "For the first irrigation, a 2% urea solution spray is beneficial for tillering. For soil application, stick to the ratio recommended by your soil health card." }] },
        { id: 104, user: { name: "Manjit Singh", avatar: "MS" }, query: "Is anyone using the 'Happy Seeder' machine? Is it worth the investment for small farms?", solutions: [{ user: { name: "Priya Sharma", avatar: "PS" }, text: "Absolutely! It saved me a lot on labour and time. Plus, it's great for soil health as it avoids stubble burning." }, { user: { name: "Ravi Kumar", avatar: "RK" }, text: "Check for government subsidies. I got a 50% subsidy on it last year through the agricultural department." }] },
        { id: 105, user: { name: "Kamaljeet", avatar: "K" }, query: "How to manage Phalaris minor (gulli danda) weed which has become resistant to Isoproturon?", solutions: [{ user: { name: "Vikram Singh", avatar: "VS" }, text: "Switch to a different herbicide group. Sulfosulfuron or Pinoxaden based herbicides are effective alternatives." }] },
        { id: 106, user: { name: "Simranjeet", avatar: "S" }, query: "What is the current MSP for wheat?", solutions: [{ user: { name: "Admin", avatar: "AD" }, text: "For the current season, the Minimum Support Price (MSP) for wheat is ₹2,275 per quintal." }] },
        { id: 107, user: { name: "Jaskaran Dhillon", avatar: "JD" }, query: "My crop is lodging (falling over) in some areas. What can be done to prevent this?", solutions: [{ user: { name: "Expert Farmer", avatar: "EF" }, text: "This could be due to excessive nitrogen or high plant density. For the next crop, ensure balanced fertilization and proper seed rate. A light irrigation can sometimes help the crop recover." }] },
        { id: 108, user: { name: "Rina Kumari", avatar: "RK" }, query: "How much has the yield increased with the new WH-1270 variety?", solutions: [{ user: { name: "Balwinder Singh", avatar: "BS" }, text: "I saw an increase of about 3-4 quintals per acre compared to my older variety. It's also more resistant to rust." }] },
        { id: 109, user: { name: "Sandeep Brar", avatar: "SB" }, query: "Best place to sell wheat directly, avoiding the mandi middleman?", solutions: [{ user: { name: "Anita Desai", avatar: "AD" }, text: "Look for local Farmer Producer Organizations (FPOs) or direct contracts with flour mills. Some apps also facilitate this now." }] },
        { id: 110, user: { name: "Amandeep", avatar: "A" }, query: "Effective ways to protect harvested grain from weevils in storage?", solutions: [{ user: { name: "Raj Patel", avatar: "RP" }, text: "Ensure the grains are properly dried (below 12% moisture). Use Ethephon pouches or consult the agriculture office for recommended fumigants." }] },
    ],
    // Queries for "Maharashtra Sugarcane Farmers"
    2: [
        { id: 201, user: { name: "Sachin Patil", avatar: "SP" }, query: "New government subsidy for drip irrigation was announced. Does anyone have the official link?", solutions: [{ user: { name: "Vidya Rao", avatar: "VR" }, text: "You can find it on the Mahadbt portal. The subsidy is part of the PMKSY scheme." }] },
        { id: 202, user: { name: "Priya Deshmukh", avatar: "PD" }, query: "My sugarcane crop is showing signs of iron deficiency (yellowing leaves). What are the recommended foliar sprays?", solutions: [{ user: { name: "G. More", avatar: "GM" }, text: "Spray Ferrous Sulphate (0.5%) mixed with a sticker. You should see results in a week." }] },
        { id: 203, user: { name: "Suresh Jadhav", avatar: "SJ" }, query: "Best practices for ratoon (khodwa) management for better yield?", solutions: [{ user: { name: "Ramesh Pawar", avatar: "RP" }, text: "Off-baring and stubble shaving are crucial. Also, apply recommended fertilizer dose immediately after harvesting the main crop." }] },
        { id: 204, user: { name: "Anjali Kulkarni", avatar: "AK" }, query: "How to control the Sugarcane Woolly Aphid infestation?", solutions: [{ user: { name: "Dr. Shinde", avatar: "DS" }, text: "Release of bio-control agents like Dipha aphidivora is the most eco-friendly and effective method. Contact the nearest agricultural university for availability." }] },
        { id: 205, user: { name: "Vikas Shinde", avatar: "VS" }, query: "Which sugarcane variety is giving the best recovery rate in the Sangli/Kolhapur region?", solutions: [{ user: { name: "Sachin Patil", avatar: "SP" }, text: "CoM 0265 (Phule 265) is still a champion variety for this region. Good yield and high sugar content." }] },
        { id: 206, user: { name: "Sunita Gaikwad", avatar: "SG" }, query: "What is the ideal spacing for planting new sugarcane for mechanical harvesting?", solutions: [{ user: { name: "Expert", avatar: "EX" }, text: "A wider spacing of at least 5 feet between rows is recommended to allow machinery to pass without damaging the crop." }] },
        { id: 207, user: { name: "Rahul Chavan", avatar: "RC" }, query: "Is anyone intercropping with sugarcane? What crop gives good returns?", solutions: [{ user: { name: "Priya Deshmukh", avatar: "PD" }, text: "I have had good success with potatoes and onions as intercrops in the initial months. They are harvested before the cane grows tall." }] },
        { id: 208, user: { name: "Kishor More", avatar: "KM" }, query: "Effective solution for white grub (humani) problem?", solutions: [{ user: { name: "Suresh Jadhav", avatar: "SJ" }, text: "Application of Metarhizium anisopliae, a bio-pesticide, in the soil before planting is a great preventive measure." }] },
        { id: 209, user: { name: "Deepak Sawant", avatar: "DS" }, query: "What is the FRP for sugarcane for the current crushing season?", solutions: [{ user: { name: "Admin", avatar: "AD" }, text: "The Fair and Remunerative Price (FRP) has been set at ₹3,150 per tonne for the 2025-26 season." }] },
        { id: 210, user: { name: "Meena Joshi", avatar: "MJ" }, query: "How can I get my soil tested in the Satara district?", solutions: [{ user: { name: "Vikas Shinde", avatar: "VS" }, text: "You can visit the district soil testing laboratory or contact the 'Krishi Sahayak' of your village." }] },
    ],
};

export const nationalQueries = [
    { id: 301, user: { name: "Priya Sharma", avatar: "PS" }, community: "Organic Farming India", query: "What is the current market rate for organic turmeric in the Delhi Azadpur Mandi?", solutions: [{ user: { name: "Vikram Reddy", avatar: "VR" }, text: "As of this morning, it was around ₹8,500/quintal for high-quality organic turmeric." }] },
    { id: 302, user: { name: "Arjun Mehta", avatar: "AM" }, community: "Indian Dairy Farmers", query: "Best fodder grass for cows during summer in Rajasthan?", solutions: [{ user: { name: "Dr. R. Singh", avatar: "RS" }, text: "Bajra Napier hybrid grass is excellent. It's drought-resistant and gives multiple cuttings." }] },
    { id: 303, user: { name: "Sita Kumari", avatar: "SK" }, community: "Organic Farming India", query: "How to prepare Jeevamrutham for a one-acre farm?", solutions: [{ user: { name: "N. Rao", avatar: "NR" }, text: "You need 10 kg cow dung, 10 litres cow urine, 2 kg jaggery, 2 kg besan, and a handful of soil. Mix in 200 litres of water and ferment for 48 hours." }] },
    { id: 304, user: { name: "Ravi Chandran", avatar: "RC" }, community: "Cotton Cultivators", query: "Is the PM-KISAN 20th installment date announced?", solutions: [{ user: { name: "Admin", avatar: "AD" }, text: "The government has indicated it will be released by the first week of December 2025. Keep an eye on the official PM-KISAN portal." }] },
    { id: 305, user: { name: "Meenakshi Iyer", avatar: "MI" }, community: "Hydroponics Innovators", query: "Where can I source good quality coco peat in bulk near Coimbatore?", solutions: [{ user: { name: "Karthik", avatar: "K" }, text: "There are several coir pith composting units near Pollachi. I can share the contact of my supplier." }] },
    { id: 306, user: { name: "Sanjay Gupta", avatar: "SG" }, community: "Organic Farming India", query: "Is there any certification required to sell products as 'organic'?", solutions: [{ user: { name: "FSSAI Help", avatar: "FH" }, text: "Yes, you need to get certified under the National Programme for Organic Production (NPOP)." }] },
    { id: 307, user: { name: "Anil Kumar", avatar: "AK" }, community: "Indian Farmers Forum", query: "How to apply for a Soil Health Card?", solutions: [{ user: { name: "Govt. Schemes", avatar: "GS" }, text: "Contact your local agriculture assistant (Krishi Sahayak). They will collect the soil sample from your farm for free." }] },
    { id: 308, user: { name: "Fatima Bi", avatar: "FB" }, community: "Cotton Cultivators", query: "Best way to manage pink bollworm without heavy pesticides?", solutions: [{ user: { name: "I. Patel", avatar: "IP" }, text: "Pheromone traps are very effective for monitoring and mass trapping. Also, destroying the crop residue after harvest is key." }] },
    { id: 309, user: { name: "Tenzin Dorjee", avatar: "TD" }, community: "Organic Farming India", query: "Tips for starting an apple orchard in Himachal Pradesh?", solutions: [{ user: { name: "Himachal Grower", avatar: "HG" }, text: "Focus on selecting the right rootstock for your altitude. Gala and Red Fuji varieties are doing very well." }] },
    { id: 310, user: { name: "Nisha Patel", avatar: "NP" }, community: "Hydroponics Innovators", query: "What is the ideal pH and EC level for growing lettuce in NFT?", solutions: [{ user: { name: "Hydro Expert", avatar: "HE" }, text: "Maintain a pH between 5.5 and 6.0. The EC should be between 1.2 and 1.8 mS/cm." }] },
];

export const globalQueries = [
    { id: 401, user: { name: "John Doe", avatar: "JD" }, community: "Global Rice Cultivators", query: "Has anyone from Southeast Asia tried the System of Rice Intensification (SRI) method? What were your results?", solutions: [{ user: { name: "Linh Nguyen", avatar: "LN" }, text: "Yes, in Vietnam we have seen a 20-30% increase in yield with SRI and it uses much less water. It is labor-intensive at the start though." }] },
    { id: 402, user: { name: "Maria Garcia", avatar: "MG" }, community: "Coffee Growers Intl.", query: "How are farmers in Colombia dealing with coffee rust (La Roya)?", solutions: [{ user: { name: "Carlos V.", avatar: "CV" }, text: "We are planting more rust-resistant varieties like Castillo and Tabi. Good farm management and timely pruning are also essential." }] },
    { id: 403, user: { name: "Dr. Emily Carter", avatar: "EC" }, community: "Agri-Tech World", query: "What's the most promising use of satellite imagery for smallholder farmers?", solutions: [{ user: { name: "David Chen", avatar: "DC" }, text: "NDVI imaging to monitor crop health and detect stress early. This is becoming more accessible through various apps." }] },
    { id: 404, user: { name: "Ahmed Al-Mansoori", avatar: "AA" }, community: "Desert Agriculture", query: "Best drip irrigation emitters for sandy soil in arid climates?", solutions: [{ user: { name: "Y. Levy", avatar: "YL" }, text: "Pressure-compensating (PC) drippers are a must to ensure uniform water distribution, especially over long distances." }] },
    { id: 405, user: { name: "Olena Kovalenko", avatar: "OK" }, community: "Sunflower Growers", query: "What's the global market outlook for sunflower oil in 2026?", solutions: [{ user: { name: "Market Analyst", avatar: "MA" }, text: "Demand is expected to remain strong, especially for high-oleic varieties. Keep an eye on production from the Black Sea region." }] },
    { id: 406, user: { name: "Ben Carter", avatar: "BC" }, community: "Vertical Farming Hub", query: "What are the best LED light spectrums for growing basil indoors?", solutions: [{ user: { name: "Jane Foster", avatar: "JF" }, text: "A higher ratio of blue light (400-500 nm) promotes vegetative growth and increases essential oil content in basil." }] },
    { id: 407, user: { name: "Fatima Zahra", avatar: "FZ" }, community: "Desert Agriculture", query: "How can we manage high soil salinity in date palm cultivation?", solutions: [{ user: { name: "Dr. Al-Farsi", avatar: "AF" }, text: "Leaching the soil with low-salinity water is the primary method. Also, applying organic matter helps improve soil structure and drainage." }] },
    { id: 408, user: { name: "William K.", avatar: "WK" }, community: "African Farmers", query: "Affordable and effective methods to control locust swarms on a small scale?", solutions: [{ user: { name: "A. Ibrahim", avatar: "AI" }, text: "Using neem-based bio-pesticides can be effective as a repellent. Community-wide monitoring and digging trenches can also help manage hopper bands." }] },
    { id: 409, user: { name: "Isabella Rossi", avatar: "IR" }, community: "Olive Growers Med.", query: "Tips for improving olive oil quality and reducing acidity?", solutions: [{ user: { name: "Marco Conti", avatar: "MC" }, text: "Harvesting the olives at the right time (not overripe) and processing them within 24 hours is the most critical factor." }] },
    { id: 410, user: { name: "Hans Müller", avatar: "HM" }, community: "Agri-Tech World", query: "Are robotic weeders becoming viable for commercial farms?", solutions: [{ user: { name: "Tech Farmer", avatar: "TF" }, text: "Yes, for high-value vegetable crops, the ROI is becoming attractive. They significantly reduce the need for herbicides and manual labor." }] },
];

export const localEvents = [
    { id: 1, title: "Pune Krishi Mela 2025", date: "Nov 15-18, 2025", location: "Pune, Maharashtra", description: "Annual agricultural exhibition showcasing new technologies, farm implements, and networking opportunities.", contact: "events@krishimela.org", link: "https://krishimela.org/register", speakers: ["Dr. Avinash K.", "Shri. Suresh Patil"] },
    { id: 2, title: "Workshop on Organic Farming", date: "Dec 05, 2025", location: "Online Webinar", description: "A deep dive into creating and using organic pesticides, with a live Q&A session.", contact: "webinars@organicindia.com", link: "https://organicindia.com/webinar", speakers: ["Dr. Meena Verma"] },
    { id: 3, title: "Nashik Grape Growers Meet", date: "Jan 10-11, 2026", location: "Nashik, Maharashtra", description: "A focused event for grape farmers to discuss export standards, new varieties, and pest management.", contact: "contact@grapeboard.in", link: "https://grapeboard.in/meet2026", speakers: ["Mr. Sahil Jagtap (Exporter)", "Dr. R. K. Singh (N.R.C. Grapes)"] },
    { id: 4, title: "Dairy Tech Expo", date: "Feb 20-22, 2026", location: "Kolhapur, Maharashtra", description: "Exhibition on modern dairy farming equipment, cattle feed, and milk processing technology.", contact: "expo@dairytech.com", link: "https://dairytechexpo.com", speakers: ["Representatives from NDDB", "Leading Veterinarians"] },
];

export const globalEvents = [
    { id: 1, title: "World Agri-Tech Innovation Summit", date: "Mar 19-20, 2026", location: "San Francisco, USA", description: "Connecting global agribusinesses with tech innovators to discuss the future of sustainable agriculture.", contact: "info@agritechsummit.com", link: "https://agritechsummit.com", speakers: ["Jane Foster (CEO, AgriGlobal)", "Dr. Kenji Tanaka"] },
    { id: 2, title: "Agritechnica 2026", date: "Nov 08-14, 2026", location: "Hanover, Germany", description: "The world's leading trade fair for agricultural machinery and technology.", contact: "info@agritechnica.com", link: "https://agritechnica.com", speakers: ["CEOs of major equipment manufacturers"] },
    { id: 3, title: "Global Forum for Food and Agriculture (GFFA)", date: "Jan 22-24, 2027", location: "Berlin, Germany", description: "An international conference on central questions concerning the future of the global agri-food industry.", contact: "contact@gffa-berlin.de", link: "https://gffa-berlin.de", speakers: ["Agriculture Ministers from 70+ countries"] },
];

export const aiLocalPrompts = [
    { id: 1, prompt: "Find best fertilizer shops near me", response: "Searching for top-rated fertilizer shops in your area with the best discounts..." },
    { id: 2, prompt: "What is the current market rate for onions?", response: "Fetching the latest market rates for onions from the nearest APMC..." },
    { id: 3, prompt: "Connect me to a soil testing service", response: "Here are the top 3 soil testing services available in your district..." },
    { id: 4, prompt: "Daily weather forecast for my farm", response: "Fetching a detailed 24-hour weather forecast, including precipitation probability and wind speed..." },
    { id: 5, prompt: "Information on PM-KISAN scheme", response: "Displaying eligibility criteria and application process for the Pradhan Mantri Kisan Samman Nidhi scheme..." },
    { id: 6, prompt: "Find nearest cold storage facility", response: "Locating cold storage facilities with available capacity in your vicinity..." },
    { id: 7, prompt: "Contact of my local 'Krishi Adhikari'", response: "Searching the official agricultural department directory for the contact details of your area's officer..." },
    { id: 8, prompt: "Identify this crop disease (via image)", response: "Please upload an image of the affected plant. I will try to identify the disease and suggest remedies." },
    { id: 9, prompt: "Best insurance for my wheat crop", response: "Analyzing available crop insurance policies under the Pradhan Mantri Fasal Bima Yojana (PMFBY) for your region..." },
    { id: 10, prompt: "Subsidies for solar water pumps", response: "Showing information on the KUSUM scheme for subsidized solar agricultural pumps..." },
];