"""Add message_type to negotiation messages

Revision ID: 10a6e52d90c3
Revises: 89f04c437d38
Create Date: 2025-09-27 10:51:40.121471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10a6e52d90c3'
down_revision: Union[str, Sequence[str], None] = '89f04c437d38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### Manually Adjusted Alembic Commands ###
    
    # Step 1: Add the new column, but allow it to be NULL temporarily.
    op.add_column('negotiation_messages', sa.Column('message_type', sa.String(length=20), nullable=True))
    
    # Step 2: Update all existing rows to have a default value.
    # 'text' is a safe default for any existing messages.
    op.execute("UPDATE negotiation_messages SET message_type = 'text' WHERE message_type IS NULL")
    
    # Step 3: Now that no rows have NULL, alter the column to be NOT NULL.
    op.alter_column('negotiation_messages', 'message_type', nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('negotiation_messages', 'message_type')
    # ### end Alembic commands ###
