"""Add forum posts and replies

Revision ID: 6c7c7b9ab4b8
Revises: 22e8fab4f156
Create Date: 2025-10-05 16:35:16.822720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c7c7b9ab4b8'
down_revision: Union[str, Sequence[str], None] = '22e8fab4f156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'contract_pdf_url')
    op.drop_column('contracts', 'buyer_signature_url')
    op.drop_column('contracts', 'farmer_signature_url')
    op.drop_column('negotiation_messages', 'message_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('negotiation_messages', sa.Column('message_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('contracts', sa.Column('farmer_signature_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('buyer_signature_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('contract_pdf_url', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
