"""Change last_offer_by to String type

Revision ID: 89f04c437d38
Revises: 
Create Date: 2025-09-26 19:26:17.331277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89f04c437d38'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
  
    # Step 1: Add the new column, but allow it to be NULL temporarily.
    op.add_column('contracts', sa.Column('last_offer_by', sa.String(length=10), nullable=True))
    
    # Step 2: Update all existing rows to have a default value. 'buyer' is a safe default.
    op.execute("UPDATE contracts SET last_offer_by = 'buyer' WHERE last_offer_by IS NULL")
    
    # Step 3: Now that no rows are NULL, alter the column to be NOT NULL.
    op.alter_column('contracts', 'last_offer_by', nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'last_offer_by')
    # ### end Alembic commands ###
