"""add farmer_signature_url to contracts table

Revision ID: ad5d790fad8f
Revises: be6ec73e6ff8
Create Date: 2025-10-10 14:42:16.443266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad5d790fad8f'
down_revision: Union[str, Sequence[str], None] = 'be6ec73e6ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('farmer_signature_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'farmer_signature_url')
    # ### end Alembic commands ###
