"""add buyer_signature_url to contracts table

Revision ID: be6ec73e6ff8
Revises: 9ffc523db87a
Create Date: 2025-10-10 10:40:11.458386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be6ec73e6ff8'
down_revision: Union[str, Sequence[str], None] = '9ffc523db87a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('buyer_signature_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'buyer_signature_url')
    # ### end Alembic commands ###
